---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "Dr. Joseph Clemente, MD"
keywords:    "Dr. Joseph Clemente, MD, Physician, Warren, NJ"
description: "Dr. Joseph Clemente, MD is a physician in Warren, NJ and has been practicing for 28 years. He graduated from Jefferson Medical College Of Thomas Jefferson University in 1985."
source_link: "https://github.com/mjclemente/drjosephclemente.com"
favicon:     #put a path like: "img/favicon.ico"
touch_icon:  #put a path like: "img/apple-touch-icon.png"
google_analytics_key: ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'

kramdown:
  auto_ids:  false

